# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.3.1
    hooks:
      - id: stylua-system # or stylua-system / stylua-github
  - repo: local
    hooks:
      - id: panvimdoc
        name: pandoc to vimdoc
        description: Convert markdown documentation to vimdoc (using local environment)
        entry: panvimdoc.pre-commit.sh
        language: system
        files: ^README\.md$
        args:
          - "--input-file"
          - README.md
          - "--project-name"
          - "winbar.nvim"
          - "--description"
          - "configurable and minimal neovim winbar"
        pass_filenames: false
